backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "index.html"
        label: "Conteúdo da Landing"
        name: "landingcontent"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
